"""
Oh My Pi (OMP) Reverse Control Mechanism (RCM) SDK & Supervisor.
Script as Control Flow, Agent as Side Watcher & Joint Time-Log Analyst.
"""

from .core import (
    AbortExecution,
    DiagnosticTrap,
    JointTimingLogEngine,
    SkipStage,
    StageMetadata,
    StageRunner,
    StateStore,
    SteeringReceiver,
    TrapInterrupt,
    WatchdogTimer,
    stage,
    apply_unified_diff,
    _transplant_callable,
    BASE_RCM_DIR,
    TELEMETRY_FILE,
    LIVE_STATUS_FILE,
    LIVE_LOGS_FILE,
    TRAPS_DIR,
    LATEST_TRAP_FILE,
    CONTROL_ACTION_FILE,
    CONTROL_SOCK_FILE,
    RAY_JOB_FILE,
    OMP_EVENT_GRAMMAR,
    parse_omp_event,
)
from .ray_job import (
    RAY_JOBS_FILE,
    RayJobInfo,
    RayJobSupervisor,
    read_active_ray_job,
    read_all_ray_jobs,
    format_ray_job_summary,
    format_ray_jobs_table,
)
from .inspect import (
    inspect_logs,
    format_inspected_logs,
    get_live_status,
    get_latest_trap,
    format_summary,
    get_active_ray_job,
)
from .cli import (
    main as cli_main,
    format_trap_system_directive,
    get_active_daemon_pid,
    stream_daemon_output,
    is_pid_alive,
    is_pid_zombie,
    cmd_run,
    cmd_resume,
    cmd_trap,
    cmd_reload,
    cmd_patch,
    cmd_steer,
    cmd_status,
    cmd_logs,
    cmd_abort,
    DAEMON_PID_FILE,
    DAEMON_LOG_FILE,
)

__all__ = [
    # Core Engine
    "AbortExecution",
    "DiagnosticTrap",
    "JointTimingLogEngine",
    "SkipStage",
    "StageMetadata",
    "StageRunner",
    "StateStore",
    "SteeringReceiver",
    "TrapInterrupt",
    "WatchdogTimer",
    "stage",
    "apply_unified_diff",
    "_transplant_callable",
    "BASE_RCM_DIR",
    "TELEMETRY_FILE",
    "LIVE_STATUS_FILE",
    "LIVE_LOGS_FILE",
    "TRAPS_DIR",
    "LATEST_TRAP_FILE",
    "CONTROL_ACTION_FILE",
    "CONTROL_SOCK_FILE",
    "RAY_JOB_FILE",
    "OMP_EVENT_GRAMMAR",
    "parse_omp_event",
    "RAY_JOBS_FILE",
    "RayJobInfo",
    "RayJobSupervisor",
    "read_active_ray_job",
    "read_all_ray_jobs",
    "format_ray_job_summary",
    "format_ray_jobs_table",
    # Telemetry & Diagnostics Inspection
    "inspect_logs",
    "format_inspected_logs",
    "get_live_status",
    "get_latest_trap",
    "format_summary",
    # CLI Supervisor & In-Flight Control
    "cli_main",
    "format_trap_system_directive",
    "get_active_daemon_pid",
    "stream_daemon_output",
    "is_pid_alive",
    "is_pid_zombie",
    "cmd_run",
    "cmd_resume",
    "cmd_trap",
    "cmd_reload",
    "cmd_patch",
    "cmd_steer",
    "cmd_status",
    "cmd_logs",
    "cmd_abort",
    "DAEMON_PID_FILE",
    "DAEMON_LOG_FILE",
]
